### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'layer_cfg'

### ISSUE THREAD

**Issue by junyuyang7** [TheJaeLal/LineFormer#2]
Hello .I run the code by you tutorial from Readme.md. But I got a mistake: AttributeError: 'ConfigDict' object has no attribute 'layer_cfg'
Can you tell me why and how to fix it?
And another question is why the paper don't mention Coco dataset, but it occur in the code. Where can I to download it?

**Comment by noahzhy** [comment]
notice that install mmcv-full first and make sure the version of your pytorch

```shell
pip install pytorch==1.13.1 torchvision==0.14.1 pytorch-cuda=11.7 -c pytorch -c nvidia
```

**Comment by TheJaeLal** [comment]
Apologies for the delayed response.
Thanks @noahzhy for the update. @junyuyang7 did that solve the problem?

@junyuyang7 
Regarding the second question, no we don't use the MS-COCO dataset for training.
We convert the existing chart datasets into [MS-COCO json annotation format](https://cocodataset.org/#format-data:~:text=1.-,Object,-Detection) for instance segmentation training, as that is what the MMDetection framework (that we use) natively supports.

Hope that helps :)

**Comment by withchencheng** [comment]
Hi @TheJaeLal I create a conda environment including the packages just as in your `install.sh`, still got this `AttributeError: 'ConfigDict' object has no attribute 'layer_cfg'`

**Comment by noahzhy** [comment]
> 你好@TheJaeLal我创建了一个 conda 环境，包括与您一样的软件包`install.sh`，但仍然得到了这个`AttributeError: 'ConfigDict' object has no attribute 'layer_cfg'`

check version of mmcv-full pls, it's work on my win PC

**Comment by noahzhy** [comment]
> Hi @TheJaeLal I create a conda environment including the packages just as in your `install.sh`, still got this `AttributeError: 'ConfigDict' object has no attribute 'layer_cfg'`

Check version of mmcv-full, it's work on my Win PC.
The detail version of mm tools, check here #1

**Comment by TheJaeLal** [comment]
Thanks @noahzhy for the response.
Closing this issue for now.
