### ISSUE TITLE
Expect your reply ！！

### ISSUE THREAD

**Issue by jiyuhao** [TheJaeLal/LineFormer#5]
This project is very meaningful, and I hope he can use it in real life in the future. Hopefully, the authors can make public how some datasets are labeled, and training files. I hope to do something better based on that. Thank you so much JaeLal !!!!

**Comment by TheJaeLal** [comment]
Sorry for the delayed response, have added the notebooks for generating the instance segmentation dataset.

**Comment by jiyuhao** [comment]
Thanks!  Good things are not afraid of being late
